export default function () {
    return [
        {
        id: 0,
        title: 'Ryzen 5 2400G',
        image: 'https://static.komputronik.pl/product-picture/5/PRYD2400C5FBBOX-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis dui leo, ut mollis nisi vestibulum vitae',
        alt: 'Ryzen 5 2400G',
        price: 599,
    },
    {
        id: 1,
        title: 'Pentium G5400',
        image: 'https://static.komputronik.pl/product-picture/5/PRYD2400C5FBBOX-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis dui leo, ut mollis nisi vestibulum vitae',
        alt: 'Pentium G5400',
        price: 369,
    },
    {
        id: 2,
        title: 'Athlon X4 870k',
        image: 'https://static.komputronik.pl/product-picture/5/PRYD2400C5FBBOX-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis dui leo, ut mollis nisi vestibulum vitae',
        alt: 'Athlon X4 870k',
        price: 199.9,
    },
    {
        id: 3,
        title: 'Core i3-8100 Tray',
        image: 'https://static.komputronik.pl/product-picture/5/PRYD2400C5FBBOX-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis dui leo, ut mollis nisi vestibulum vitae',
        alt: 'Core i3-8100 Tray',
        price: 139,
    },
    {
        id: 4,
        title: 'Ryzen Threadripper 2990WX',
        image: 'https://static.komputronik.pl/product-picture/5/PRYD2400C5FBBOX-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis dui leo, ut mollis nisi vestibulum vitae',
        alt: 'Ryzen Threadripper 2990WX',
        price: 1569,
    },
    {
        id: 5,
        title: 'Xeon Processor E5-2680 v4',
        image: 'https://static.komputronik.pl/product-picture/5/PRYD2400C5FBBOX-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis dui leo, ut mollis nisi vestibulum vitae',
        alt: 'Xeon Processor E5-2680 v4',
        price: 9990,
    },
    {
        id: 6,
        title: 'Celeron G4920',
        image: 'https://static.komputronik.pl/product-picture/5/PRYD2400C5FBBOX-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis dui leo, ut mollis nisi vestibulum vitae',
        alt: 'Celeron G4920',
        price: 289,
    },
    {
        id: 7,
        title: 'A12 9800E',
        image: 'https://static.komputronik.pl/product-picture/5/PRYD2400C5FBBOX-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis dui leo, ut mollis nisi vestibulum vitae',
        alt: 'A12 9800E',
        price: 449,
    },
    {
        id: 8,
        title: 'APU A6-7400K',
        image: 'https://static.komputronik.pl/product-picture/5/PRYD2400C5FBBOX-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis dui leo, ut mollis nisi vestibulum vitae',
        alt: 'APU A6-7400K',
        price: 169.9,
    },
    {
        id: 9,
        title: 'X8 FX-8350 Wraith',
        image: 'https://static.komputronik.pl/product-picture/5/PRYD2400C5FBBOX-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis dui leo, ut mollis nisi vestibulum vitae',
        alt: 'X8 FX-8350 Wraith',
        price: 349,
    },
    {
        id: 10,
        title: 'Celeron G3930',
        image: 'https://static.komputronik.pl/product-picture/5/PRYD2400C5FBBOX-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis dui leo, ut mollis nisi vestibulum vitae',
        alt: 'Celeron G3930',
        price: 219,
    },
    {
        id: 11,
        title: 'Core i7-8700',
        image: 'https://static.komputronik.pl/product-picture/5/PRYD2400C5FBBOX-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis dui leo, ut mollis nisi vestibulum vitae',
        alt: 'Core i7-8700',
        price: 1529,
    },
    {
        id: 12,
        title: 'Ryzen 7 2700 MAX',
        image: 'https://static.komputronik.pl/product-picture/5/PRYD2400C5FBBOX-1.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis dui leo, ut mollis nisi vestibulum vitae',
        alt: 'Ryzen 7 2700 MAX',
        price: 219,
    },
    
]
};

